name: GitHub Actions Secrets

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve secrets
        run: echo "Stripe secret key is ${{ secrets.STRIPE_SECRET_KEY }}"
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
