name: GitHub Actions Secrets

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: echo "Stripe secret key es ${{ secrets.STRIPE_SECRET_KEY }}"
