name: GitHub Actions Secrets

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    steps:
      - name: Retrieve secrets
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

